### ISSUE TITLE
nag compiler with DEBUG on case failing

### ISSUE THREAD

**Issue by ekluzek** [marysa/SimpleLand#21]
A longer DEBUG on case is failing on izumi with the nag compiler:

SMS_D_Lm1.f19_g17.I2000SlimRsGs.izumi_nag.clm-2000_CMIP6_AMIP_1deg_ensemble

The traceback looks like this:

```
[i032.unified.ucar.edu:mpi_rank_62][error_sighandler] Caught error: Aborted (signal 6)
 line 125: Called by CIME_DRIVER
[i032.unified.ucar.edu:mpi_rank_63][error_sighandler] Caught error: Aborted (signal 6)
e 125: Called by CIME_DRIVER
[i032.unified.ucar.edu:mpi_rank_64][error_sighandler] Caught error: Aborted (signal 6)
CIME_DRIVER
[i032.unified.ucar.edu:mpi_rank_65][error_sighandler] Caught error: Aborted (signal 6)
/fs/cgd/data0/erik/slim_cesm21/src/main/histFileMod.F90, line 1612: Error occurred in HISTFILEMOD:HIST_UPDATE_HBUF_FIELD_2D
/fs/cgd/data0/erik/slim_cesm21/src/main/histFileMod.F90, line 1038: Called by HISTFILEMOD:HIST_UPDATE_HBUF
/fs/cgd/data0/erik/slim_cesm21/src/main/clm_driver.F90, line 166: Called by CLM_DRIVER:CLM_DRV
/fs/cgd/data0/erik/slim_cesm21/src/cpl/lnd_comp_mct.F90, line 476: Called by LND_COMP_MCT:LND_RUN_MCT
/fs/cgd/data0/erik/slim_cesm21/cime/src/drivers/mct/main/component_mod.F90, line 728: Called by COMPONENT_MOD:COMPONENT_RUN
/fs/cgd/data0/erik/slim_cesm21/cime/src/drivers/mct/main/cime_comp_mod.F90, line 2720: Called by CIME_COMP_MOD:CIME_RUN
/fs/cgd/data0/erik/slim_cesm21/cime/src/drivers/mct/main/cime_driver.F90, line 125: Called by CIME_DRIVER
```

The same case with gnu passes fine:

SMS_D_Lm1.f19_g17.I2000SlimRsGs.izumi_gnu.clm-2000_CMIP6_AMIP_1deg_ensemble

**Comment by ekluzek** [comment]
The intel case also fails on cheyenne. The gnu case works fine on both cheyenne and intel.

The backtrace for intel is similar to above:

```
681:MPT: Missing separate debuginfos, use: zypper install glibc-debuginfo-2.22-49.16.x86_64
681:MPT: (gdb) #0  0x00002b7233f8f6da in waitpid ()
681:MPT:    from /glade/u/apps/ch/os/lib64/libpthread.so.0
681:MPT: #1  0x00002b7234dd7db6 in mpi_sgi_system (
681:MPT: #2  MPI_SGI_stacktraceback (
681:MPT:     header=header@entry=0x7ffdc65920c0 "MPT ERROR: Rank 681(g:681) received signal SIGFPE(8).\n\tProcess ID: 25390, Host: r5i1n29, Program: /glade/scratch/erik/SMS_D_Lm1.f19_g17.I2000SlimRsGs.cheyenne_intel.clm-2000_CMIP6_AMIP_1deg_ensemble.G"...) at sig.c:340
681:MPT: #3  0x00002b7234dd7fb2 in first_arriver_handler (signo=signo@entry=8,
681:MPT:     stack_trace_sem=stack_trace_sem@entry=0x2b723f420080) at sig.c:489
681:MPT: #4  0x00002b7234dd834b in slave_sig_handler (signo=8, siginfo=<optimized out>,
681:MPT:     extra=<optimized out>) at sig.c:564
681:MPT: #5  <signal handler called>
681:MPT: #6  0x00000000009577fc in histfilemod::hist_update_hbuf_field_2d (t=1, f=171,
681:MPT:     bounds=..., num2d=2)
681:MPT:     at /glade/work/erik/slim_cesm21/src/main/histFileMod.F90:1612
```

**Comment by ekluzek** [comment]
The intel case worked in 8a8ffd3a42dddefbf0c35228c24374e42b21f30f, so perhaps this is an intermittent failure?

**Comment by ekluzek** [comment]
The nag case is now working, so I'm going to declare this as working. Reducing complexity seems to have helped here...
